# Generated by Django 4.2.11 on 2024-05-04 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="created_at",
            field=models.DateTimeField(verbose_name=datetime.datetime.now),
        ),
    ]
